/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;

// Trying to keep the class compatable with Java8. Otherwise, we can just make it a record.
public class Division {
    private String m_name;
    private List<String> m_depts;

    public Division(String name, List<String> depts) {
        m_name = name;
        this.m_depts = depts;
    }

    public List<String> getDepts() {
        return m_depts;
    }

    public void setDepts(List<String> depts) {
        this.m_depts = depts;
    }

    public String getName() {
        return m_name;
    }

    public void setName(String name) {
        m_name = name;
    }

    @Override
    public String toString() {
        return "Division [m_name=" + m_name + ", m_depts=" + m_depts + "]";
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((m_name == null) ? 0 : m_name.hashCode());
        result = prime * result + ((m_depts == null) ? 0 : m_depts.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Division other = (Division) obj;
        if (m_name == null) {
            if (other.m_name != null)
                return false;
        } else if (!m_name.equals(other.m_name))
            return false;
        if (m_depts == null) {
            if (other.m_depts != null)
                return false;
        } else if (!m_depts.equals(other.m_depts))
            return false;
        return true;
    }
}
