/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test 
    void appHasAGreeting() throws IOException {
        System.out.println(Files.readAllLines(Paths.get("src/test/resources/test1/master_file.txt")));

    }
}
